import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import { CheckCircle2 } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ToastContainer
          position="top-right"
          toastClassName="bg-black/90 backdrop-blur-xl border border-red-500/30 text-white rounded-lg shadow-[0_0_20px_rgba(255,40,40,0.15)]"
          progressClassName="bg-red-500"
          icon={<CheckCircle2 className="text-red-500" size={20} />}
        />
        {children}
      </body>
    </html>
  );
}
